### ISSUE TITLE
parse error with timing_distribution: 'duration' was unexpected

### ISSUE THREAD

**Issue by bdekoz** [mozilla/glean_parser#95]
* Glean Parser version: 1.4.2
* Python version:
Python 2.7.16
Python 3.7.4
* Operating System:
Linux varney.localdomain 5.2.11-200.fc30.x86_64 #1 SMP Thu Aug 29 12:43:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Description

I'm integrating the performance/graphics metrics here:
https://docs.google.com/spreadsheets/d/1EZGVGmybvF1sH-XrsXMlplK7fWQfDniIeqXrkfDQrlc/edit#gid=0

to fenix using glean.

To do this, I'm using this branch of gecko, with the following modifications to
m-c/toolkit/components/telemetry/Histograms.json
https://github.com/bdekoz/gecko/commit/0add4785dca93a27bf6c2d015238739a259b3982

With this branch of fenix, which has app/metrics.yaml edits as per
https://github.com/bdekoz/fenix/commit/8e3b402c701d5445d6082057d5e0a78c422f3cf1

To smash these suckers together, I'm building a local geckoview as per these directions, the
"Dependency substiting your local GeckoView into a Mozilla project" part:
https://github.com/mozilla/geckoview/blob/gh-pages/contributor/geckoview-quick-start.md

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

I'm hoping to get a nightly built, using the telemetry as defined. Install it on android. Then load a few sites, got to "about:telemetry" and inspect the JSON, and see the new histograms.

### What I Did

See above, then enter the fenix source directory, and type

./gradlew assembleDebug

Which gives:

 subprocess.check_call([
      sys.executable,
      '-m',
      module_name
  ] + sys.argv[3:])
  , glean_parser, 1.4.2, translate, -f, kotlin, -o, /home/bkoz/src/mozilla-fenix-bdekoz-fork.git/app/build/generated/source/glean/geckoBeta/debug/kotlin, -s, namespace=org.mozilla.fenix.GleanMetrics, -s, glean_namespace=mozilla.components.service.glean, /home/bkoz/src/mozilla-fenix-bdekoz-fork.git/app/metrics.yaml, /home/bkoz/src/mozilla-fenix-bdekoz-fork.git/app/pings.yaml, /home/bkoz/.gradle/caches/transforms-2/files-2.1/5f41b25223c80abfa33aba09059852a9/jetified-geckoview-default-71.0.20190905192215/metrics.yaml]' finished with non-zero exit value 1:
  
  ==============================================================================
  /home/bkoz/src/mozilla-fenix-bdekoz-fork.git/app/metrics.yaml:
      ```
      metrics:
        composite_time:
          duration:
            bugs:
            - 1080160
            - 1529352
            data_reviews:
            - https://bugzilla.mozilla.org/show_bug.cgi?id=1529352
            description: 'Composite times in milliseconds.
      
              '
            expires: '2020-12-01'
            gecko_datapoint: COMPOSITE_TIME
            notification_emails:
            - telemetry-performance-dev@mozilla.com
            time_unit: millisecond
            type: timing_distribution
      ```
      
      Additional properties are not allowed ('duration' was unexpected)
      
      Documentation for this node:
          Describes a single metric.
          
          See https://mozilla.github.io/glean_parser/metrics-yaml.html
  ==============================================================================
  /home/bkoz/src/mozilla-fenix-bdekoz-fork.git/app/metrics.yaml:
      ```
      metrics:
        composite_time:
          duration:
            bugs:
            - 1080160
            - 1529352
            data_reviews:
            - https://bugzilla.mozilla.org/show_bug.cgi?id=1529352
            description: 'Composite times in milliseconds.
      
              '
            expires: '2020-12-01'
            gecko_datapoint: COMPOSITE_TIME
            notification_emails:
            - telemetry-performance-dev@mozilla.com
            time_unit: millisecond
            type: timing_distribution
      ```
      
      Missing required properties: bugs, data_reviews, description, expires,
      notification_emails, type
      
      Documentation for this node:
          Describes a single metric.
          
          See https://mozilla.github.io/glean_parser/metrics-yaml.html

[build.20190905.log](https://github.com/mozilla/glean_parser/files/3582294/build.20190905.log)

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Dexterp37** [comment]
Thank you for reaching out, Benjamin.

Please note that we have [documentation for adding Gecko metrics through Glean](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/start/report-gecko-telemetry-in-glean.html), which provides a step by step example.

# General observations

While this is not the reason why you're seeing that failure, the changes to the Fenix repo are not required and even though you might manage to make Fenix build, no streaming telemetry will be collected that way.

As shown in the guide, metrics need to be added to the [`metrics.yaml` file in the Gecko repository](https://hg.mozilla.org/mozilla-central/file/tip/toolkit/components/telemetry/geckoview/streaming/metrics.yaml). No Gecko metrics will be exfiltrated otherwise. The `engine-gecko-*` components in Android Components take care of stitching things together, so Gecko metrics need to be where it expects them to be.

> I'm hoping to get a nightly built, using the telemetry as defined. Install it on android. Then load a few sites, got to "about:telemetry" and inspect the JSON, and see the new histograms.

This won't work. `about:telemetry` is not supported, is a legacy page that should not be available at all in Fenix. The [Glean debug ping view](https://docs.telemetry.mozilla.org/concepts/glean/debug_ping_view.html) should be used instead.

# Specific problem breaking the compilation
Glean metrics [need a category and a name](https://mozilla.github.io/glean/book/user/adding-new-metrics.html). The metric you are adding has additional indentation and its living under the [mis-named category](https://mozilla.github.io/glean/book/user/adding-new-metrics.html#naming-things) `metrics`, in Fenix. The parser is seeing this as

```
metrics: <- category
  ...
  composite_time: <- parser sees this as the metric name
    duration: <- parser sees this as a property, and doesn't know about that name
      type: timing_distribution
```

Since we're here, I would recommend to provide more specific naming as described  [here](https://mozilla.github.io/glean/book/user/adding-new-metrics.html#naming-things).

```
gfx.composite:
  duration:
    type: timing_distribution
    ...
```
